## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">PART- 02- MISSIG VALLUE ANALYSIS</p>

In [1]:
import pandas as pd
import numpy as np

# Load the data generated from Notebook 
df = pd.read_csv("../data/processed/clean_data.csv")

# Display the percentage of missing values per column to map your targets
missing_percentages = df.isnull().mean() * 100
#print("Missing Value Percentages:\n", missing_percentages[missing_percentages > 0])

In [2]:
df.head(3).T

,0,1,2
make_model,Audi A1,Audi A1,Audi A1
body_type,Sedans,Sedans,Sedans
price,15770,14500,14640
vat,VAT deductible,Price negotiable,VAT deductible
km,56013.0,80000.0,83450.0
hp,66.0,141.0,85.0
type,Used,Used,Used
inspection_new,Yes,NaN,NaN
warranty,4.0,NaN,99.0
body_color,Black,Red,Black
paint_type,Metallic,NaN,Metallic
nr_of_doors,5.0,3.0,4.0
nr_of_seats,5.0,4.0,4.0
gearing_type,Automatic,Automatic,Automatic
displacement,1422.0,1798.0,1598.0
cylinders,3.0,4.0,NaN
weight,1220.0,1255.0,NaN
drive_chain,front,front,front
fuel,Diesel,Benzine,Diesel
co2_emission,99.0,129.0,99.0
emission_class,Euro 6,Euro 6,Euro 6
comfort_and_convenience,"'Air conditioning', 'Armrest', 'Automatic clim...","'Air conditioning', 'Automatic climate control...","'Air conditioning', 'Cruise control', 'Electri..."
entertainment_and_media,"'Bluetooth', 'Hands-free equipment', 'On-board...","'Bluetooth', 'Hands-free equipment', 'On-board...","'MP3', 'On-board computer'"
extras,"Alloy wheels,Catalytic Converter,Voice Control","Alloy wheels,Sport seats,Sport suspension,Voic...","Alloy wheels,Voice Control"
safety_and_security,"ABS,Central door lock,Daytime running lights,D...","ABS,Central door lock,Central door lock with r...","ABS,Central door lock,Daytime running lights,D..."
gears,NaN,7.0,NaN
registration_year,2016.0,2017.0,2016.0
age,3.0,2.0,3.0
upholstery_type,Cloth,Cloth,Cloth
upholstery_color,Black,Grey,Black
cons_comb,3.8,5.6,3.8
cons_city,4.3,7.1,4.4
cons_country,3.5,4.7,3.4

In [3]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'hp', 'type',
       'inspection_new', 'warranty', 'body_color', 'paint_type', 'nr_of_doors',
       'nr_of_seats', 'gearing_type', 'displacement', 'cylinders', 'weight',
       'drive_chain', 'fuel', 'co2_emission', 'emission_class',
       'comfort_and_convenience', 'entertainment_and_media', 'extras',
       'safety_and_security', 'gears', 'registration_year', 'age',
       'upholstery_type', 'upholstery_color', 'cons_comb', 'cons_city',
       'cons_country'],
      dtype='object')

In [4]:
# function for first looking to the columns

def first_looking(col):
    print("column name    : ", col)
    print("--------------------------------")
    print("per_of_nulls   : ", "%", round(df[col].isnull().sum()*100 / df.shape[0], 2))
    print("num_of_nulls   : ", df[col].isnull().sum())
    print("num_of_uniques : ", df[col].nunique())
    print("--------------------------------")
    print(df[col].value_counts(dropna = False))

In [5]:
miss_val = []

[miss_val.append(column) for column in df.columns if any(df[column].isnull())]

print("Columns that have missing values :")

miss_val

Columns that have missing values :

['body_type',
 'vat',
 'km',
 'hp',
 'type',
 'inspection_new',
 'warranty',
 'body_color',
 'paint_type',
 'nr_of_doors',
 'nr_of_seats',
 'displacement',
 'cylinders',
 'weight',
 'drive_chain',
 'co2_emission',
 'comfort_and_convenience',
 'entertainment_and_media',
 'extras',
 'safety_and_security',
 'gears',
 'registration_year',
 'age',
 'upholstery_type',
 'upholstery_color',
 'cons_comb',
 'cons_city',
 'cons_country']

In [6]:
first_looking("age")

column name    :  age
--------------------------------
per_of_nulls   :  % 10.03
num_of_nulls   :  1597
num_of_uniques :  4
--------------------------------
1.0    4522
3.0    3674
2.0    3273
0.0    2853
NaN    1597
Name: age, dtype: int64

In [7]:
#describe() does NOT return anything for "NaN" values. 
#If you have "Nan" at the column you are interested in, 
#you should replace these "nan" values with something else. 
#In our case, we have replaced the "NaN" values with "-" 
#so that we could implement the "describe" method.

df['age'].fillna('-', inplace=True)

In [8]:
df["age"].value_counts(dropna=False)

1.0    4522
3.0    3674
2.0    3273
0.0    2853
-      1597
Name: age, dtype: int64

In [9]:
df.groupby("age").km.describe()

,count,mean,std,min,25%,50%,75%,max
age,,,,,,,,
0.0,2706.0,2085.355137,5365.880693,1.0,10.00,50.0,3000.0,127022.0
1.0,4484.0,18035.239072,11052.524314,1.0,9990.00,17872.0,25078.5,136000.0
2.0,3272.0,41754.940709,28295.747886,1.0,21541.75,34752.0,54805.5,317000.0
3.0,3674.0,77442.520958,39170.142977,10.0,48000.00,72914.5,99950.0,291800.0
-,759.0,934.496706,7416.243875,0.0,5.00,10.0,10.0,89982.0

In [10]:
df[df["age"] == "-"]["km"].value_counts(dropna=False)

NaN        838
10.0       369
1.0        146
5.0         58
20.0        32
15.0        21
0.0         19
11.0        12
8.0         11
50.0        10
12.0         8
100.0        8
7.0          7
3.0          4
9.0          4
4.0          3
250.0        3
25.0         3
30.0         3
3000.0       2
39962.0      2
2.0          2
22627.0      2
784.0        1
89692.0      1
3500.0       1
325.0        1
497.0        1
99.0         1
77.0         1
40.0         1
19500.0      1
6100.0       1
11000.0      1
89982.0      1
4307.0       1
141.0        1
34164.0      1
500.0        1
150.0        1
11200.0      1
20768.0      1
32084.0      1
142.0        1
81800.0      1
281.0        1
6.0          1
68485.0      1
85000.0      1
196.0        1
4500.0       1
60.0         1
5000.0       1
Name: km, dtype: int64

In [11]:
cond1 = (df['km'] < 10000)
cond2 = ((df['km'] >= 10000) & (df['km'] < 28000))
cond3 = ((df['km'] >= 28000) & (df['km'] < 50000))
cond4 = (df['km'] >= 50000)

In [12]:
df.loc[cond1,'age'] = df.loc[cond1,'age'].replace('-', 0)
df.loc[cond2,'age'] = df.loc[cond2,'age'].replace('-', 1)
df.loc[cond3,'age'] = df.loc[cond3,'age'].replace('-', 2)
df.loc[cond4,'age'] = df.loc[cond4,'age'].replace('-', 3)

In [13]:
df.groupby('age').km.mean()

age
0.0     1647.362609
1.0    18035.130067
2.0    41748.576923
3.0    77450.062789
-               NaN
Name: km, dtype: float64

In [14]:
df["age"].value_counts(dropna=False)

1.0    4528
3.0    3679
0.0    3597
2.0    3277
-       838
Name: age, dtype: int64

In [15]:
df.groupby(['make_model',"body_type", 'age']).price.describe()

                              count          mean          std      min  \
make_model     body_type age
Audi A1        Compact   0.0  198.0  23277.434343  3510.405726  14900.0
                         1.0  268.0  18596.041045  2659.909876  13980.0
                         2.0  161.0  16602.807453  2085.383788  10999.0
                         3.0  234.0  14532.910256  1908.908968   9950.0
                         -    178.0  23996.264045  3383.852477  16220.0
...                             ...           ...          ...      ...
Renault Espace Van       0.0  218.0  40074.513761  8154.729111  24200.0
                         1.0  207.0  31947.840580  4072.970330  23099.0
                         2.0  134.0  26574.477612  3427.862590  14600.0
                         3.0  199.0  22132.623116  3216.031594  12614.0
                         -     19.0  39632.315789  6866.138589  28650.0

                                  25%      50%       75%      max
make_model     body_type age
Audi A1        Compact   0.0  20503.5  22492.0  26798.50  31990.0
                         1.0  16445.0  16980.0  20950.00  23829.0
                         2.0  15450.0  15850.0  17700.00  22150.0
                         3.0  13407.5  13994.5  15480.00  18900.0
                         -    21515.0  22875.0  27380.00  29181.0
...                               ...      ...       ...      ...
Renault Espace Van       0.0  32975.0  38925.0  45667.25  68320.0
                         1.0  29385.0  31900.0  34990.00  38990.0
                         2.0  24982.5  25490.0  28500.00  33800.0
                         3.0  19900.0  22222.0  24650.00  27900.0
                         -    33848.0  39550.0  45950.50  50170.0

[176 rows x 8 columns]

In [16]:
df['age'].replace('-', 0, inplace=True)

In [17]:
df.groupby('age').km.mean()

age
0.0     1647.362609
1.0    18035.130067
2.0    41748.576923
3.0    77450.062789
Name: km, dtype: float64

In [18]:
df["age"].value_counts(dropna=False)

1.0    4528
0.0    4435
3.0    3679
2.0    3277
Name: age, dtype: int64

In [19]:
first_looking("km")

column name    :  km
--------------------------------
per_of_nulls   :  % 6.43
num_of_nulls   :  1024
num_of_uniques :  6689
--------------------------------
10.0       1045
NaN        1024
1.0         367
5.0         170
50.0        148
           ...
67469.0       1
43197.0       1
10027.0       1
35882.0       1
57.0          1
Name: km, Length: 6690, dtype: int64

In [20]:
df.groupby("age").km.mean()

age
0.0     1647.362609
1.0    18035.130067
2.0    41748.576923
3.0    77450.062789
Name: km, dtype: float64

In [21]:
df[df["km"].isna()][["age", "km"]]

       age  km
743    0.0 NaN
869    0.0 NaN
946    0.0 NaN
977    0.0 NaN
980    0.0 NaN
...    ...  ..
15890  0.0 NaN
15902  0.0 NaN
15912  0.0 NaN
15914  0.0 NaN
15918  0.0 NaN

[1024 rows x 2 columns]

In [22]:
# Let us use transform() function to fill missing values at "km" column with "mean".

In [23]:
df.groupby("age").km.transform("mean")

0        77450.062789
1        41748.576923
2        77450.062789
3        77450.062789
4        77450.062789
             ...
15914     1647.362609
15915     1647.362609
15916     1647.362609
15917     1647.362609
15918     1647.362609
Name: km, Length: 15919, dtype: float64

In [24]:
df["km"].fillna(df.groupby("age").km.transform("mean"), inplace=True)

In [25]:
df[df["km"].isna()][["age", "km"]]

Empty DataFrame
Columns: [age, km]
Index: []

In [26]:
df.km.value_counts(dropna=False)

10.000000       1045
1647.362609      985
1.000000         367
5.000000         170
50.000000        148
                ...
67469.000000       1
43197.000000       1
10027.000000       1
35882.000000       1
57.000000          1
Name: km, Length: 6692, dtype: int64

In [27]:
#body_type

In [28]:
df.body_type.value_counts(dropna=False)

Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
NaN                60
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64

In [29]:
df[df.body_type.isnull()]

,make_model,body_type,price,vat,km,hp,type,inspection_new,warranty,body_color,...,extras,safety_and_security,gears,registration_year,age,upholstery_type,upholstery_color,cons_comb,cons_city,cons_country
3175,Audi A3,NaN,14400,NaN,119000.000000,81.0,Used,NaN,NaN,Black,...,"Alloy wheels,Sport package,Trailer hitch,Voice...","ABS,Adaptive headlights,Central door lock,Cent...",6.0,2016.0,3.0,Cloth,NaN,3.8,4.5,3.4
3255,Audi A3,NaN,18500,Price negotiable,70000.000000,81.0,Used,NaN,NaN,White,...,"Alloy wheels,Shift paddles","ABS,Alarm system,Central door lock,Driver-side...",7.0,2016.0,3.0,Cloth,Beige,3.8,4.3,3.5
3975,Audi A3,NaN,19950,NaN,25000.000000,85.0,Used,NaN,6.0,Blue,...,"Alloy wheels,Roof rack,Sport package,Sport sea...","ABS,Adaptive headlights,Central door lock with...",7.0,2017.0,2.0,NaN,NaN,4.7,5.6,4.2
3997,Audi A3,NaN,19750,VAT deductible,38800.000000,82.0,Used,NaN,6.0,Black,...,Alloy wheels,"ABS,Daytime running lights,Driver-side airbag,...",NaN,2017.0,2.0,NaN,NaN,NaN,NaN,NaN
4206,Audi A3,NaN,18490,NaN,20000.000000,92.0,Used,NaN,NaN,White,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2017.0,2.0,NaN,NaN,5.1,6.7,4.1
4297,Audi A3,NaN,17990,NaN,20000.000000,92.0,Used,NaN,NaN,White,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2017.0,2.0,NaN,NaN,5.1,6.7,4.1
4298,Audi A3,NaN,17990,NaN,20000.000000,92.0,Used,NaN,NaN,White,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2017.0,2.0,NaN,NaN,5.1,6.7,4.1
5718,Opel Astra,NaN,12990,NaN,47000.000000,100.0,Used,NaN,NaN,Black,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2016.0,3.0,NaN,NaN,4.5,5.7,3.8
5938,Opel Astra,NaN,12990,NaN,47000.000000,100.0,Used,NaN,NaN,Black,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2016.0,3.0,NaN,NaN,4.5,5.7,3.8
5940,Opel Astra,NaN,12990,NaN,47000.000000,100.0,Used,NaN,NaN,Black,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2016.0,3.0,NaN,NaN,4.5,5.7,3.8
6920,Opel Astra,NaN,11990,NaN,64000.000000,81.0,Used,NaN,NaN,Black,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2017.0,2.0,NaN,NaN,3.7,4.2,3.3
6922,Opel Astra,NaN,11990,NaN,64000.000000,81.0,Used,NaN,NaN,Black,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2017.0,2.0,NaN,NaN,3.7,4.2,3.3
6927,Opel Astra,NaN,11990,NaN,64000.000000,81.0,Used,NaN,NaN,Black,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2017.0,2.0,NaN,NaN,3.7,4.2,3.3
7709,Opel Astra,NaN,26490,NaN,6000.000000,112.0,Used,NaN,NaN,Grey,...,NaN,NaN,NaN,2019.0,0.0,NaN,NaN,NaN,NaN,NaN
8408,Opel Corsa,NaN,12435,VAT deductible,21050.000000,44.0,Used,Yes,NaN,White,...,"Alloy wheels,Sport seats","ABS,Central door lock,Daytime running lights,D...",5.0,2018.0,1.0,Cloth,Black,NaN,NaN,NaN
8584,Opel Corsa,NaN,8900,NaN,43731.000000,51.0,Used,NaN,NaN,Black,...,"Alloy wheels,Catalytic Converter,Handicapped e...","ABS,Adaptive Cruise Control,Adaptive headlight...",NaN,2017.0,2.0,NaN,NaN,NaN,NaN,NaN
10837,Opel Insignia,NaN,11490,NaN,99000.000000,125.0,Used,NaN,NaN,Black,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2017.0,2.0,NaN,NaN,5.6,7.8,4.2
10838,Opel Insignia,NaN,11490,NaN,99000.000000,125.0,Used,NaN,NaN,Black,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2017.0,2.0,NaN,NaN,5.6,7.8,4.2
10857,Opel Insignia,NaN,11490,NaN,99000.000000,125.0,Used,NaN,NaN,Black,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2017.0,2.0,NaN,NaN,5.6,7.8,4.2
13430,Renault Clio,NaN,7990,VAT deductible,76021.000000,67.0,Used,NaN,NaN,White,...,Sport package,"ABS,Daytime running lights,Driver-side airbag,...",NaN,2016.0,3.0,NaN,NaN,NaN,NaN,NaN
13470,Renault Clio,NaN,8490,NaN,39990.000000,55.0,Used,NaN,NaN,White,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2018.0,1.0,NaN,NaN,NaN,NaN,NaN
13576,Renault Clio,NaN,7980,VAT deductible,79980.000000,56.0,Used,NaN,3.0,White,...,Sport package,"ABS,Daytime running lights,Driver-side airbag,...",NaN,2016.0,3.0,NaN,NaN,NaN,NaN,NaN
13703,Renault Clio,NaN,7690,VAT deductible,63372.000000,56.0,Used,NaN,6.0,White,...,NaN,"ABS,Electronic stability control,Fog lights",NaN,2017.0,2.0,NaN,NaN,NaN,NaN,NaN
13725,Renault Clio,NaN,7490,VAT deductible,69031.000000,56.0,Used,NaN,6.0,White,...,NaN,"ABS,Electronic stability control,Fog lights",NaN,2017.0,2.0,NaN,NaN,NaN,NaN,NaN
13852,Renault Clio,NaN,8500,NaN,34564.000000,55.0,Used,NaN,NaN,White,...,NaN,"ABS,Power steering",NaN,2017.0,2.0,NaN,NaN,NaN,NaN,NaN
13900,Renault Clio,NaN,9490,VAT deductible,84496.000000,56.0,Used,NaN,NaN,White,...,NaN,"ABS,Daytime running lights,Driver-side airbag,...",NaN,2017.0,2.0,NaN,NaN,NaN,NaN,NaN
14107,Renault Clio,NaN,9990,NaN,39000.000000,55.0,Used,NaN,NaN,White,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2017.0,2.0,NaN,NaN,3.3,3.5,3.1
14124,Renault Clio,NaN,9990,VAT deductible,15.000000,56.0,Used,NaN,NaN,White,...,Sport package,"ABS,Daytime running lights,Driver-side airbag,...",NaN,2018.0,1.0,NaN,NaN,NaN,NaN,NaN
14127,Renault Clio,NaN,9990,VAT deductible,15.000000,56.0,Used,NaN,NaN,White,...,Sport package,"ABS,Daytime running lights,Driver-side airbag,...",NaN,2018.0,1.0,NaN,NaN,NaN,NaN,NaN
14134,Renault Clio,NaN,9980,VAT deductible,10.000000,56.0,Used,NaN,NaN,White,...,"Roof rack,Sport package","ABS,Central door lock,Daytime running lights,D...",NaN,2018.0,1.0,NaN,NaN,NaN,NaN,NaN
14135,Renault Clio,NaN,9980,VAT deductible,10.000000,56.0,Used,NaN,NaN,White,...,"Roof rack,Sport package","ABS,Central door lock,Daytime running lights,D...",NaN,2018.0,1.0,NaN,NaN,NaN,NaN,NaN
14480,Renault Clio,NaN,10000,NaN,8000.000000,54.0,Used,NaN,NaN,Red,...,NaN,"ABS,Central door lock,Central door lock with r...",5.0,2018.0,1.0,Cloth,Black,5.6,7.2,4.7
14869,Renault Clio,NaN,10850,VAT deductible,10.000000,56.0,New,NaN,NaN,Grey,...,NaN,"ABS,Central door lock,Driver-side airbag,Elect...",5.0,NaN,0.0,Cloth,Black,5.0,6.4,4.2
14870,Renault Clio,NaN,10850,VAT deductible,10.000000,56.0,New,NaN,NaN,Black,...,NaN,"ABS,Central door lock,Driver-side airbag,Elect...",5.0,NaN,0.0,Cloth,Black,5.0,6.4,4.2
14928,Renault Espace,NaN,17500,NaN,141000.000000,118.0,Used,NaN,NaN,White,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2016.0,3.0,NaN,NaN,4.6,5.0,4.4
14990,Renault Espace,NaN,26800,NaN,332.000000,165.0,Used,NaN,NaN,Grey,...,NaN,NaN,7.0,2018.0,1.0,NaN,NaN,6.8,8.7,5.6
15058,Renault Espace,NaN,24990,NaN,45000.000000,118.0,Used,NaN,NaN,White,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2017.0,2.0,NaN,NaN,4.6,5.0,4.4
15059,Renault Espace,NaN,24990,NaN,45000.000000,118.0,Used,NaN,NaN,White,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2017.0,2.0,NaN,NaN,4.6,5.0,4.4
15060,Renault Espace,NaN,24990,NaN,45000.000000,118.0,Used,NaN,NaN,White,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2017.0,2.0,NaN,NaN,4.6,5.0,4.4
15124,Renault Espace,NaN,24500,NaN,58078.000000,118.0,Used,NaN,NaN,Grey,...,NaN,NaN,6.0,2016.0,3.0,NaN,NaN,4.6,5.0,4.4
15269,Renault Espace,NaN,17500,NaN,141000.000000,118.0,Used,NaN,NaN,White,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2016.0,3.0,NaN,NaN,4.6,5.0,4.4
15275,Renault Espace,NaN,17500,NaN,141000.000000,118.0,Used,NaN,NaN,White,...,NaN,"ABS,Central door lock,Daytime running lights,D...",NaN,2016.0,3.0,NaN,NaN,4.6,5.0,4.4
15289,Renault Espace,NaN,28140,NaN,10.000000,96.0,Used,NaN,NaN,Grey,...,NaN,NaN,6.0,NaN,0.0,NaN,NaN,4.4,5.1,4.0
15307,Renault Espace,NaN,31000,NaN,10.000000,96.0,Used,NaN,NaN,Grey,...,NaN,NaN,6.0,NaN,0.0,NaN,NaN,4.4,5.1,4.0
15378,Renault Espace,NaN,26450,NaN,10.000000,96.0,Used,NaN,NaN,Grey,...,NaN,NaN,6.0,NaN,0.0,NaN,NaN,4.4,5.1,4.0
15437,Renault Espace,NaN,33000,VAT deductible,18035.130067,118.0,Pre-registered,NaN,NaN,Black,...,Touch screen,"ABS,Alarm system,Driver-side airbag,Electronic...",6.0,2018.0,1.0,NaN,NaN,4.7,5.1,4.4
15452,Renault Espace,NaN,33300,NaN,10.000000,118.0,Used,NaN,NaN,Grey,...,NaN,NaN,6.0,NaN,0.0,NaN,NaN,4.6,5.0,4.4
15456,Renault Espace,NaN,33400,NaN,886.000000,118.0,Used,NaN,NaN,Black,...,NaN,NaN,6.0,2018.0,1.0,NaN,NaN,4.6,5.0,4.4
15457,Renault Espace,NaN,33400,NaN,454.000000,118.0,Used,NaN,NaN,White,...,NaN,NaN,6.0,2018.0,1.0,NaN,NaN,4.6,5.0,4.4
15488,Renault Espace,NaN,32600,NaN,10.000000,165.0,Used,NaN,NaN,Grey,...,NaN,NaN,7.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
15489,Renault Espace,NaN,32576,VAT deductible,10100.000000,118.0,Used,NaN,NaN,Black,...,"Alloy wheels,Touch screen,Voice Control","ABS,Adaptive Cruise Control,Blind spot monitor...",6.0,2018.0,1.0,Full leather,Brown,4.6,5.0,4.4
15491,Renault Espace,NaN,32576,VAT deductible,10100.000000,118.0,Used,NaN,NaN,Black,...,"Alloy wheels,Touch screen,Voice Control","ABS,Adaptive Cruise Control,Blind spot monitor...",6.0,2018.0,1.0,Full leather,Brown,4.6,5.0,4.4
15499,Renault Espace,NaN,32200,NaN,10.000000,165.0,Used,NaN,NaN,Grey,...,NaN,NaN,7.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
15544,Renault Espace,NaN,29750,NaN,10.000000,165.0,Used,NaN,NaN,Grey,...,NaN,NaN,7.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
15556,Renault Espace,NaN,30160,NaN,10.000000,118.0,Used,NaN,NaN,Grey,...,NaN,NaN,6.0,NaN,0.0,NaN,NaN,4.6,5.0,4.4
15589,Renault Espace,NaN,31000,VAT deductible,18035.130067,118.0,Pre-registered,NaN,NaN,White,...,NaN,"ABS,Driver-side airbag,Electronic stability co...",6.0,2018.0,1.0,NaN,NaN,4.7,5.1,4.4
15696,Renault Espace,NaN,38200,VAT deductible,1.000000,118.0,Pre-registered,NaN,NaN,Black,...,Touch screen,"ABS,Alarm system,Driver-side airbag,Electronic...",6.0,2019.0,0.0,NaN,NaN,4.7,5.1,4.4
15712,Renault Espace,NaN,37100,VAT deductible,1.000000,118.0,Pre-registered,NaN,NaN,White,...,NaN,"ABS,Driver-side airbag,Electronic stability co...",6.0,2019.0,0.0,NaN,NaN,4.7,5.1,4.4
15736,Renault Espace,NaN,35448,NaN,10.000000,165.0,Used,NaN,NaN,Grey,...,NaN,NaN,7.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
15770,Renault Espace,NaN,35930,NaN,10.000000,118.0,Used,NaN,NaN,Grey,...,NaN,NaN,6.0,NaN,0.0,NaN,NaN,4.6,5.0,4.4

In [30]:
df[df.body_type==np.nan]

Empty DataFrame
Columns: [make_model, body_type, price, vat, km, hp, type, inspection_new, warranty, body_color, paint_type, nr_of_doors, nr_of_seats, gearing_type, displacement, cylinders, weight, drive_chain, fuel, co2_emission, emission_class, comfort_and_convenience, entertainment_and_media, extras, safety_and_security, gears, registration_year, age, upholstery_type, upholstery_color, cons_comb, cons_city, cons_country]
Index: []

[0 rows x 33 columns]

In [31]:
df["body_type"].value_counts(dropna=False)

Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
NaN                60
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64

In [32]:
df.groupby('make_model')['body_type'].transform(lambda x: x.mode()[0])

0        Sedans
1        Sedans
2        Sedans
3        Sedans
4        Sedans
          ...
15914       Van
15915       Van
15916       Van
15917       Van
15918       Van
Name: body_type, Length: 15919, dtype: object

In [33]:
df["body_type"].fillna(df.groupby('make_model')['body_type'].transform(lambda x: x.mode()[0]), inplace=True)

In [34]:
#registration

In [35]:
df['registration_year']

0        2016.0
1        2017.0
2        2016.0
3        2016.0
4        2016.0
          ...
15914       NaN
15915    2019.0
15916    2019.0
15917    2019.0
15918    2019.0
Name: registration_year, Length: 15919, dtype: float64

In [36]:
df['type']

0                  Used
1                  Used
2                  Used
3                  Used
4                  Used
              ...
15914               New
15915              Used
15916    Pre-registered
15917    Pre-registered
15918     Demonstration
Name: type, Length: 15919, dtype: object

In [37]:
df.loc[((df['type'] == 'New') & df.registration_year.isnull()), 'registration_year'] = 2019

In [38]:
df.groupby('registration_year').km.mean()

registration_year
2016.0    77442.520958
2017.0    41754.938765
2018.0    18035.238156
2019.0     1651.826754
Name: km, dtype: float64

In [39]:
# Since the registration of all new cars is 2019, 
# null values of year column of new cars filled with 2019.

In [40]:
df.loc[(df['registration_year'].isnull()) & (df.km <= 5000),'registration_year'] =2019

In [41]:
df.loc[(df['registration_year'].isnull()) & (df.km > 50000),'registration_year'] =2016

In [42]:
df.loc[(df['registration_year'].isnull()) & (df.km < 19000),'registration_year'] =2018

In [43]:
df.loc[(df['registration_year'].isnull()) & (df.km < 40000),'registration_year'] =2017

In [44]:
#Rest of the null values were filled according to km of autos.
df[(df['make_model'] == 'Audi A3') & (df['body_type'] == 'Sedans')].groupby('registration_year').price.mean()

registration_year
2016.0    16702.052388
2017.0    19970.030631
2018.0    22544.715092
2019.0    24860.812139
Name: price, dtype: float64

In [45]:
df[(df['make_model'] == 'Opel Insignia')].groupby('registration_year').price.mean()

registration_year
2016.0    13606.709507
2017.0    16995.140917
2018.0    21390.167750
2019.0    32104.553571
Name: price, dtype: float64

In [46]:
df.loc[(df['registration_year'].isnull())]

Empty DataFrame
Columns: [make_model, body_type, price, vat, km, hp, type, inspection_new, warranty, body_color, paint_type, nr_of_doors, nr_of_seats, gearing_type, displacement, cylinders, weight, drive_chain, fuel, co2_emission, emission_class, comfort_and_convenience, entertainment_and_media, extras, safety_and_security, gears, registration_year, age, upholstery_type, upholstery_color, cons_comb, cons_city, cons_country]
Index: []

[0 rows x 33 columns]

In [47]:
df['registration_year']=df['registration_year'].fillna(2019)

In [48]:
#VAT
#All null values of vat column assigned as 'VAT undeductible'

In [49]:
df.vat.value_counts(dropna=False)

VAT deductible      10980
NaN                  4513
Price negotiable      426
Name: vat, dtype: int64

In [50]:
df['vat'] = df['vat'].fillna('VAT undeductible')

In [51]:
#KM
#km column filled with groups age, make_model and body_type

In [52]:
median_group_km = df.groupby(['make_model','body_type','age']).km.transform(lambda x: x.median())

In [53]:
df["km"].fillna(df.groupby(['make_model','age']).km.transform(lambda x: x.median()), inplace=True)

In [54]:
# Previous Owner

In [55]:
index=df[df["km"]<10].index

In [56]:
df.loc[index,"prev_owner"]=0.0

In [57]:
df.loc[(df["type"]=="New") & (df["prev_owner"].isnull()),"prev_owner"]=1.0

In [58]:
df.loc[((df["age"]==2019) | (df["km"]<5000)) & (df["prev_owner"].isnull()),"prev_owner"]=1.0

In [59]:
mode_group_po = df.groupby(['age'])['prev_owner'].transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [60]:
df["prev_owner"].fillna(mode_group_po, inplace=True)

In [61]:
#hp

In [62]:
mode_hp = df[~(df['displacement'].isnull())]\
              .groupby(['make_model','body_type','displacement'])['hp']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [63]:
df.loc[~(df['displacement'].isnull()),"hp"] = df.loc[~(df['displacement'].isnull()),"hp"].fillna(mode_hp)

In [64]:
mode_hp1 = df[~(df['cylinders'].isnull())]\
              .groupby(['make_model','body_type','cylinders'])['hp']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [65]:
df.loc[~(df['cylinders'].isnull()),"hp"] = df.loc[~(df['cylinders'].isnull()),"hp"].fillna(mode_hp1)

In [66]:
mode_hp2 = df.groupby(['make_model','body_type'])['hp']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [67]:
df['hp'] = df['hp'].fillna(mode_hp2)

In [68]:
#Type

In [69]:
df['type'] = df['type'].fillna('Used')

In [70]:
#Inspection New

In [71]:
df['inspection_new'].value_counts(dropna=False)

NaN    11987
Yes     3932
Name: inspection_new, dtype: int64

In [72]:
df["inspection_new"].fillna("-", inplace=True)

In [73]:
df["inspection_new"].replace("-", "No", inplace=True)

In [74]:
df['inspection_new'].value_counts(dropna=False)

No     11987
Yes     3932
Name: inspection_new, dtype: int64

In [75]:
#Warranty
#warranty column was filled with 0's

In [76]:
df['warranty'] = df['warranty'].fillna(0.0)

In [77]:
#Body Color

In [78]:
mode_color = df.groupby(['make_model','body_type'])['body_color']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [79]:
df["body_color"] = df["body_color"].fillna(mode_color)

In [80]:
mode_color2 = df.groupby(['make_model'])['body_color']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [81]:
df["body_color"] = df["body_color"].fillna(mode_color2)

In [82]:
df['body_color'].value_counts(dropna=False)

Black     3941
Grey      3839
White     3469
Silver    1647
Blue      1431
Red        957
Brown      289
Green      158
Beige      108
Yellow      51
Violet      18
Bronze       6
Orange       3
Gold         2
Name: body_color, dtype: int64

In [83]:
# Paint Type

In [84]:
first_looking("paint_type")

column name    :  paint_type
--------------------------------
per_of_nulls   :  % 36.26
num_of_nulls   :  5772
num_of_uniques :  3
--------------------------------
Metallic       9794
NaN            5772
Uni/basic       347
Perl effect       6
Name: paint_type, dtype: int64

In [85]:
mode_paint = df.groupby(['make_model','body_type'])['paint_type']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [86]:
df['paint_type'] = df['paint_type'].fillna(mode_paint)

In [87]:
mode_paint1 = df.groupby(['make_model'])['paint_type']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [88]:
df['paint_type'] = df['paint_type'].fillna(mode_paint1)

In [89]:
# upholstery_color

In [90]:
df.drop("upholstery_color", axis=1, inplace=True)

In [91]:
#Nr. of Doors

In [92]:
mode_nr_doors = df.groupby(['make_model','body_type'])['nr_of_doors']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [93]:
df['nr_of_doors'] = df['nr_of_doors'].fillna(mode_nr_doors)

In [94]:
mode_nr_doors1 = df.groupby(['make_model'])['nr_of_doors']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [95]:
df['nr_of_doors'] = df['nr_of_doors'].fillna(mode_nr_doors1)

In [96]:
#Nr. of Seats

In [97]:
mode_nr_seats = df.groupby(['make_model','body_type'])['nr_of_seats']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [98]:
df['nr_of_seats'] = df['nr_of_seats'].fillna(mode_nr_seats)

In [99]:
mode_nr_seats1 = df.groupby(['make_model'])['nr_of_seats']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [100]:
df['nr_of_seats'] = df['nr_of_seats'].fillna(mode_nr_seats1)

In [101]:
# Gearing Type
df['gearing_type'].value_counts(dropna=False)

Manual            8153
Automatic         7297
Semi-automatic     469
Name: gearing_type, dtype: int64

In [102]:
# Displacement
# Displacement column was filled according to groups hp, make_model, body_type

In [103]:
mode_displacement = df.groupby(['make_model','body_type','hp'])['displacement']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [104]:
df['displacement'] = df['displacement'].fillna(mode_displacement)

In [105]:
mode_displacement1 = df.groupby(['make_model','body_type'])['displacement']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [106]:
df['displacement'] = df['displacement'].fillna(mode_displacement1)

In [107]:
mode_displacement2 = df.groupby(['make_model'])['displacement']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [108]:
df['displacement'] = df['displacement'].fillna(mode_displacement2)

In [109]:
# Weight
# weight column was filled according to groups hp, make_model, body_type

In [110]:
mode_weight = df.groupby(['make_model', 'displacement'])['weight']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [111]:
df['weight'] = df['weight'].fillna(mode_weight)

In [112]:
mode_weight1 = df.groupby(['make_model'])['weight']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [113]:
df['weight'] = df['weight'].fillna(mode_weight1)

In [114]:
mode_weight2 = df.groupby(['make_model', 'hp'])['weight']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [115]:
df['weight'] = df['weight'].fillna(mode_weight2)

In [116]:
mode_weight3 = df.groupby(['body_type'])['weight']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [117]:
df['weight'] = df['weight'].fillna(mode_weight3)

In [118]:
df['weight'].value_counts(dropna=False)

1163.0    1519
1360.0    1047
1135.0     877
1503.0     660
1425.0     604
          ...
1960.0       1
1258.0       1
1167.0       1
1331.0       1
2037.0       1
Name: weight, Length: 434, dtype: int64

In [119]:
# Cylinders
# cylinders column was filled according to groups displacement, weight, make_mode

In [120]:
mode_cylinders = df.groupby(['make_model', 'displacement'])['cylinders']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [121]:
df['cylinders'] = df['cylinders'].fillna(mode_cylinders)

In [122]:
mode_cylinders1 = df.groupby(['make_model', 'weight'])['cylinders']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [123]:
df['cylinders'] = df['cylinders'].fillna(mode_cylinders1)

In [124]:
mode_cylinders2 = df.groupby(['make_model'])['cylinders']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [125]:
df['cylinders'] = df['cylinders'].fillna(mode_cylinders2)

In [126]:
df['cylinders'] = df['cylinders'].fillna(4.0)

In [127]:
# Drive Chain
# drive_chain column was filled according to groups make_model and body type

In [128]:
mode_drive_chain = df.groupby(['make_model', 'body_type'])['drive_chain']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [129]:
df['drive_chain'] = df['drive_chain'].fillna(mode_drive_chain)

In [130]:
mode_drive_chain1 = df.groupby(['make_model'])['drive_chain']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [131]:
df['drive_chain'] = df['drive_chain'].fillna(mode_drive_chain1)

In [132]:
# Fuel
df['fuel'].value_counts(dropna=False)

Benzine     8551
Diesel      7299
LPG/CNG       64
Electric       5
Name: fuel, dtype: int64

In [133]:
# CO2 Emission(g CO2/km)
# CO2 Emission(g CO2/km)' column was filled according 
# to groups make_model,displacement and body type

In [134]:
mode_CO2 = df.groupby(['make_model','displacement'])['co2_emission']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [135]:
df['co2_emission'] = df['co2_emission'].fillna(mode_CO2)

In [136]:
mode_CO2_1 = df.groupby(['make_model'])['co2_emission']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [137]:
df['co2_emission'] = df['co2_emission'].fillna(mode_CO2_1)

In [138]:
mode_CO2_2 = df.groupby(['body_type'])['co2_emission']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [139]:
df['co2_emission'] = df['co2_emission'].fillna(mode_CO2_2)

In [140]:
# Emission Class
# Emission class column was filled according to groups co2 emission and age

In [141]:
mode_Emision_C= df.groupby(['co2_emission'])['emission_class']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [142]:
df['emission_class'] = df['emission_class'].fillna(mode_Emision_C)

In [143]:
mode_Emision_C1= df.groupby(['age'])['emission_class']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [144]:
df['emission_class'] = df['emission_class'].fillna(mode_Emision_C1)

In [145]:
df['emission_class'].value_counts()

Euro 6    12173
-          3628
Euro 5       78
Euro 4       40
Name: emission_class, dtype: int64

In [146]:
# Gears
# Gears column was filled according to groups make model and gear type

In [147]:
mode_Gears= df.groupby(['make_model','gearing_type'])['gears']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [148]:
df['gears'] = df['gears'].fillna(mode_Gears)

In [149]:
mode_Gears1= df.groupby(['gearing_type'])['gears']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [150]:
df['gears'] = df['gears'].fillna(mode_Gears1)

In [151]:
# upholstery_type

In [152]:
df['upholstery_type'].value_counts(dropna=False)

Cloth           8423
NaN             4871
Part leather    1499
Full leather    1009
Velour            60
alcantara         57
Name: upholstery_type, dtype: int64

In [153]:
# Consumption Combined

# comsumption column first was filled with the mean 
# of 'consumption_city','consumption_country' columns. 
# Then was filled according to the column make_model.

In [154]:
coms = ((df['cons_city']+df['cons_country'])/2)

In [155]:
df['cons_comb'] = df['cons_comb'].fillna(coms)

In [156]:
mode_Cons= df.groupby(['co2_emission'])['cons_comb']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [157]:
df['cons_comb'] = df['cons_comb'].fillna(mode_Cons)

In [158]:
mode_Cons1= df.groupby(['displacement'])['cons_comb']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [159]:
df['cons_comb'] = df['cons_comb'].fillna(mode_Cons1)

In [160]:
mode_Cons2= df.groupby(['make_model'])['cons_comb']\
              .transform(lambda x: x.mode()[0] if list(x.mode()) != [] else np.nan)

In [161]:
df['cons_comb'] = df['cons_comb'].fillna(mode_Cons2)

In [162]:
df.shape

(15919, 33)

In [163]:
#cons_country
df.drop("cons_country", axis = 1, inplace = True)

In [164]:
# cons_city
df.drop("cons_city", axis = 1, inplace = True)

In [165]:
df.shape

(15919, 31)

In [166]:
# 
df.to_csv("../data/processed/missings_filled.csv", index=False)